// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WheatTrace.Infrastructure.Data;

#nullable disable

namespace WheatTrace.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WheatTraceDbContext))]
    [Migration("20260409191930_MakeMessageSiteIdNullable")]
    partial class MakeMessageSiteIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WheatTrace.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<TimeSpan?>("RecurringEndTime")
                        .HasColumnType("interval")
                        .HasColumnName("recurring_end_time");

                    b.Property<TimeSpan?>("RecurringStartTime")
                        .HasColumnType("interval")
                        .HasColumnName("recurring_start_time");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_announcements");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("i_x_announcements_created_by_id");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.AssignmentTransferRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("FromGovernorateId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_governorate_id");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspector_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_shift_id");

                    b.Property<Guid>("TargetSiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_site_id");

                    b.Property<Guid>("ToGovernorateId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_governorate_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_assignment_transfer_requests");

                    b.HasIndex("ApprovedById")
                        .HasDatabaseName("i_x_assignment_transfer_requests_approved_by_id");

                    b.HasIndex("FromGovernorateId")
                        .HasDatabaseName("i_x_assignment_transfer_requests_from_governorate_id");

                    b.HasIndex("InspectorId")
                        .HasDatabaseName("i_x_assignment_transfer_requests_inspector_id");

                    b.HasIndex("RequestedById")
                        .HasDatabaseName("i_x_assignment_transfer_requests_requested_by_id");

                    b.HasIndex("TargetShiftId")
                        .HasDatabaseName("i_x_assignment_transfer_requests_target_shift_id");

                    b.HasIndex("TargetSiteId")
                        .HasDatabaseName("i_x_assignment_transfer_requests_target_site_id");

                    b.HasIndex("ToGovernorateId")
                        .HasDatabaseName("i_x_assignment_transfer_requests_to_governorate_id");

                    b.ToTable("assignment_transfer_requests", t =>
                        {
                            t.HasCheckConstraint("chk_transfer_diff_governorate", "\"from_governorate_id\" <> \"to_governorate_id\"");
                        });
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_audit_logs");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Authority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_authorities");

                    b.ToTable("authorities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(7035),
                            IsActive = true,
                            Name = "الشركة المصرية القابضة للصوامع"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(7037),
                            IsActive = true,
                            Name = "الشركة العامة للصوامع والتخزين"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(7038),
                            IsActive = true,
                            Name = "شركات المطاحن"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(7039),
                            IsActive = true,
                            Name = "البنك الزراعي المصري"
                        });
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.DailyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspector_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<long>("TotalQtyKg")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("total_qty_kg")
                        .HasComputedColumnSql("(\"wheat22_5_ton\" * 1000 + \"wheat22_5_kg\") + (\"wheat23_ton\"   * 1000 + \"wheat23_kg\"  ) + (\"wheat23_5_ton\" * 1000 + \"wheat23_5_kg\")", true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Wheat22_5Kg")
                        .HasColumnType("integer")
                        .HasColumnName("wheat22_5_kg");

                    b.Property<int>("Wheat22_5Ton")
                        .HasColumnType("integer")
                        .HasColumnName("wheat22_5_ton");

                    b.Property<int>("Wheat23Kg")
                        .HasColumnType("integer")
                        .HasColumnName("wheat23_kg");

                    b.Property<int>("Wheat23Ton")
                        .HasColumnType("integer")
                        .HasColumnName("wheat23_ton");

                    b.Property<int>("Wheat23_5Kg")
                        .HasColumnType("integer")
                        .HasColumnName("wheat23_5_kg");

                    b.Property<int>("Wheat23_5Ton")
                        .HasColumnType("integer")
                        .HasColumnName("wheat23_5_ton");

                    b.HasKey("Id")
                        .HasName("p_k_daily_entries");

                    b.HasIndex("InspectorId")
                        .HasDatabaseName("i_x_daily_entries_inspector_id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("i_x_daily_entries_shift_id");

                    b.HasIndex("SiteId", "Date")
                        .IsUnique()
                        .HasDatabaseName("uix_daily_entry_site_date_no_shift")
                        .HasFilter("\"shift_id\" IS NULL");

                    b.HasIndex("SiteId", "Date", "ShiftId")
                        .IsUnique()
                        .HasDatabaseName("uix_daily_entry_site_date_shift")
                        .HasFilter("\"shift_id\" IS NOT NULL");

                    b.ToTable("daily_entries");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uuid")
                        .HasColumnName("governorate_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_districts");

                    b.HasIndex("GovernorateId")
                        .HasDatabaseName("i_x_districts_governorate_id");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.EditRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<decimal?>("NewWheat22_5")
                        .HasColumnType("numeric")
                        .HasColumnName("new_wheat22_5");

                    b.Property<decimal?>("NewWheat23")
                        .HasColumnType("numeric")
                        .HasColumnName("new_wheat23");

                    b.Property<decimal?>("NewWheat23_5")
                        .HasColumnType("numeric")
                        .HasColumnName("new_wheat23_5");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_edit_requests");

                    b.HasIndex("ApprovedById")
                        .HasDatabaseName("i_x_edit_requests_approved_by_id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("i_x_edit_requests_entry_id");

                    b.HasIndex("RequestedById")
                        .HasDatabaseName("i_x_edit_requests_requested_by_id");

                    b.ToTable("edit_requests");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Governorate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_governorates");

                    b.ToTable("governorates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6772),
                            IsActive = true,
                            Name = "القاهرة"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6777),
                            IsActive = true,
                            Name = "الأسكندرية"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6778),
                            IsActive = true,
                            Name = "بورسعيد"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6779),
                            IsActive = true,
                            Name = "السويس"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6781),
                            IsActive = true,
                            Name = "الدقهلية"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6782),
                            IsActive = true,
                            Name = "الشرقية"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6784),
                            IsActive = true,
                            Name = "القليوبية"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6785),
                            IsActive = true,
                            Name = "كفر الشيخ"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6786),
                            IsActive = true,
                            Name = "الغربية"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6787),
                            IsActive = true,
                            Name = "المنوفية"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6789),
                            IsActive = true,
                            Name = "البحيرة"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6790),
                            IsActive = true,
                            Name = "الإسماعيلية"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6791),
                            IsActive = true,
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6792),
                            IsActive = true,
                            Name = "بني سويف"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6793),
                            IsActive = true,
                            Name = "الفيوم"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6794),
                            IsActive = true,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6796),
                            IsActive = true,
                            Name = "أسيوط"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6797),
                            IsActive = true,
                            Name = "سوهاج"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6798),
                            IsActive = true,
                            Name = "قنا"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6800),
                            IsActive = true,
                            Name = "أسوان"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6801),
                            IsActive = true,
                            Name = "الأقصر"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6802),
                            IsActive = true,
                            Name = "البحر الأحمر"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000023"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6803),
                            IsActive = true,
                            Name = "الوادي الجديد"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000024"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6804),
                            IsActive = true,
                            Name = "مطروح"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000025"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6806),
                            IsActive = true,
                            Name = "شمال سيناء"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000026"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6807),
                            IsActive = true,
                            Name = "جنوب سيناء"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000027"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(6808),
                            IsActive = true,
                            Name = "دمياط"
                        });
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<Guid?>("GovernorateId")
                        .HasColumnType("uuid")
                        .HasColumnName("governorate_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_holidays");

                    b.HasIndex("GovernorateId")
                        .HasDatabaseName("i_x_holidays_governorate_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_holidays_site_id");

                    b.ToTable("holidays");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.InspectorAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignment_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspector_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_inspector_assignments");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("i_x_inspector_assignments_shift_id");

                    b.HasIndex("InspectorId", "Date")
                        .IsUnique()
                        .HasDatabaseName("uix_assignment_inspector_date_active")
                        .HasFilter("\"is_active\" = true");

                    b.HasIndex("SiteId", "Date", "ShiftId")
                        .IsUnique()
                        .HasDatabaseName("uix_assignment_site_date_shift_active")
                        .HasFilter("\"is_active\" = true AND \"shift_id\" IS NOT NULL");

                    b.ToTable("inspector_assignments");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.InspectorMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_message_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientInspectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_inspector_id");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_inspector_messages");

                    b.HasIndex("ParentMessageId")
                        .HasDatabaseName("i_x_inspector_messages_parent_message_id");

                    b.HasIndex("RecipientInspectorId")
                        .HasDatabaseName("i_x_inspector_messages_recipient_inspector_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("i_x_inspector_messages_sender_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_inspector_messages_site_id");

                    b.ToTable("inspector_messages");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Rejection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DailyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_entry_id");

                    b.Property<decimal>("ImpuritiesTon")
                        .HasColumnType("numeric")
                        .HasColumnName("impurities_ton");

                    b.Property<decimal>("InsectDamageTon")
                        .HasColumnType("numeric")
                        .HasColumnName("insect_damage_ton");

                    b.Property<decimal>("MoistureTon")
                        .HasColumnType("numeric")
                        .HasColumnName("moisture_ton");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<decimal>("SandGravelTon")
                        .HasColumnType("numeric")
                        .HasColumnName("sand_gravel_ton");

                    b.Property<decimal>("TotalRejectionTon")
                        .HasColumnType("numeric")
                        .HasColumnName("total_rejection_ton");

                    b.Property<decimal>("TreatedQuantityTon")
                        .HasColumnType("numeric")
                        .HasColumnName("treated_quantity_ton");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_rejections");

                    b.HasIndex("DailyEntryId")
                        .IsUnique()
                        .HasDatabaseName("uix_rejection_entry");

                    b.ToTable("rejections", t =>
                        {
                            t.HasCheckConstraint("chk_rejection_buckets_total", "\"moisture_ton\" + \"sand_gravel_ton\" + \"impurities_ton\" + \"insect_damage_ton\" <= \"total_rejection_ton\"");

                            t.HasCheckConstraint("chk_rejection_treated", "\"treated_quantity_ton\" <= \"total_rejection_ton\"");
                        });
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.SeasonSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackupJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DownloadToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("download_token");

                    b.Property<string>("SeasonLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season_label");

                    b.Property<bool>("TokenUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("token_used");

                    b.Property<int>("TotalSites")
                        .HasColumnType("integer")
                        .HasColumnName("total_sites");

                    b.Property<double>("TotalTons")
                        .HasColumnType("double precision")
                        .HasColumnName("total_tons");

                    b.HasKey("Id")
                        .HasName("p_k_season_snapshots");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("i_x_season_snapshots_created_by_id");

                    b.ToTable("season_snapshots");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_shifts");

                    b.ToTable("shifts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(7069),
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsActive = true,
                            Name = "الوردية الأولى (الصباحية)",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 4, 9, 19, 19, 25, 478, DateTimeKind.Utc).AddTicks(7073),
                            EndTime = new TimeSpan(0, 0, 0, 0, 0),
                            IsActive = true,
                            Name = "الوردية الثانية (المسائية)",
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.SiteLifecycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("RecordedById")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<decimal>("StockSnapshotKg")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_snapshot_kg");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_site_lifecycle_events");

                    b.HasIndex("RecordedById")
                        .HasDatabaseName("i_x_site_lifecycle_events_recorded_by_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_site_lifecycle_events_site_id");

                    b.ToTable("site_lifecycle_events");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.StockTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorizedById")
                        .HasColumnType("uuid")
                        .HasColumnName("authorized_by_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalDestination")
                        .HasColumnType("text")
                        .HasColumnName("external_destination");

                    b.Property<Guid>("FromSiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_site_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ToSiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_site_id");

                    b.Property<DateOnly>("TransferDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_date");

                    b.Property<long>("TransferQtyKg")
                        .HasColumnType("bigint")
                        .HasColumnName("transfer_qty_kg");

                    b.Property<Guid?>("TriggerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_event_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehicleInfo")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_info");

                    b.Property<int>("Wheat22_5Kg")
                        .HasColumnType("integer")
                        .HasColumnName("wheat22_5_kg");

                    b.Property<int>("Wheat22_5Ton")
                        .HasColumnType("integer")
                        .HasColumnName("wheat22_5_ton");

                    b.Property<int>("Wheat23Kg")
                        .HasColumnType("integer")
                        .HasColumnName("wheat23_kg");

                    b.Property<int>("Wheat23Ton")
                        .HasColumnType("integer")
                        .HasColumnName("wheat23_ton");

                    b.Property<int>("Wheat23_5Kg")
                        .HasColumnType("integer")
                        .HasColumnName("wheat23_5_kg");

                    b.Property<int>("Wheat23_5Ton")
                        .HasColumnType("integer")
                        .HasColumnName("wheat23_5_ton");

                    b.HasKey("Id")
                        .HasName("p_k_stock_transfers");

                    b.HasIndex("AuthorizedById")
                        .HasDatabaseName("i_x_stock_transfers_authorized_by_id");

                    b.HasIndex("FromSiteId")
                        .HasDatabaseName("i_x_stock_transfers_from_site_id");

                    b.HasIndex("ToSiteId")
                        .HasDatabaseName("i_x_stock_transfers_to_site_id");

                    b.HasIndex("TriggerEventId")
                        .HasDatabaseName("i_x_stock_transfers_trigger_event_id");

                    b.ToTable("stock_transfers", t =>
                        {
                            t.HasCheckConstraint("chk_transfer_diff_sites", "\"from_site_id\" <> \"to_site_id\"");

                            t.HasCheckConstraint("chk_transfer_positive_qty", "\"transfer_qty_kg\" > 0");
                        });
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.StorageSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid")
                        .HasColumnName("authority_id");

                    b.Property<long>("CapacityKg")
                        .HasColumnType("bigint")
                        .HasColumnName("capacity_kg");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CurrentStockKg")
                        .HasColumnType("bigint")
                        .HasColumnName("current_stock_kg");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<DateOnly?>("ExceptionEndDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_end_date");

                    b.Property<DateOnly?>("ExceptionStartDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_start_date");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uuid")
                        .HasColumnName("governorate_id");

                    b.Property<bool>("IsShiftEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shift_enabled");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationText")
                        .HasColumnType("text")
                        .HasColumnName("location_text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("TotalReceivedKg")
                        .HasColumnType("bigint")
                        .HasColumnName("total_received_kg");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_storage_sites");

                    b.HasIndex("AuthorityId")
                        .HasDatabaseName("i_x_storage_sites_authority_id");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("i_x_storage_sites_district_id");

                    b.HasIndex("GovernorateId")
                        .HasDatabaseName("i_x_storage_sites_governorate_id");

                    b.ToTable("storage_sites");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GovernorateId")
                        .HasColumnType("uuid")
                        .HasColumnName("governorate_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("GovernorateId")
                        .HasDatabaseName("i_x_users_governorate_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_announcements__users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.AssignmentTransferRequest", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .HasConstraintName("f_k_assignment_transfer_requests__users_approved_by_id");

                    b.HasOne("WheatTrace.Domain.Entities.Governorate", "FromGovernorate")
                        .WithMany()
                        .HasForeignKey("FromGovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assignment_transfer_requests__governorates_from_governorate_~");

                    b.HasOne("WheatTrace.Domain.Entities.User", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assignment_transfer_requests__users_inspector_id");

                    b.HasOne("WheatTrace.Domain.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assignment_transfer_requests__users_requested_by_id");

                    b.HasOne("WheatTrace.Domain.Entities.Shift", "TargetShift")
                        .WithMany()
                        .HasForeignKey("TargetShiftId")
                        .HasConstraintName("f_k_assignment_transfer_requests__shifts_target_shift_id");

                    b.HasOne("WheatTrace.Domain.Entities.StorageSite", "TargetSite")
                        .WithMany()
                        .HasForeignKey("TargetSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assignment_transfer_requests__storage_sites_target_site_id");

                    b.HasOne("WheatTrace.Domain.Entities.Governorate", "ToGovernorate")
                        .WithMany()
                        .HasForeignKey("ToGovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assignment_transfer_requests__governorates_to_governorate_id");

                    b.Navigation("ApprovedBy");

                    b.Navigation("FromGovernorate");

                    b.Navigation("Inspector");

                    b.Navigation("RequestedBy");

                    b.Navigation("TargetShift");

                    b.Navigation("TargetSite");

                    b.Navigation("ToGovernorate");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.DailyEntry", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.User", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_daily_entries__users_inspector_id");

                    b.HasOne("WheatTrace.Domain.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .HasConstraintName("f_k_daily_entries__shifts_shift_id");

                    b.HasOne("WheatTrace.Domain.Entities.StorageSite", "Site")
                        .WithMany("DailyEntries")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_daily_entries__storage_sites_site_id");

                    b.Navigation("Inspector");

                    b.Navigation("Shift");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.District", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.Governorate", "Governorate")
                        .WithMany("Districts")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_districts__governorates_governorate_id");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.EditRequest", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .HasConstraintName("f_k_edit_requests__users_approved_by_id");

                    b.HasOne("WheatTrace.Domain.Entities.DailyEntry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_edit_requests_daily_entries_entry_id");

                    b.HasOne("WheatTrace.Domain.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_edit_requests__users_requested_by_id");

                    b.Navigation("ApprovedBy");

                    b.Navigation("Entry");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Holiday", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .HasConstraintName("f_k_holidays_governorates_governorate_id");

                    b.HasOne("WheatTrace.Domain.Entities.StorageSite", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .HasConstraintName("f_k_holidays__storage_sites_site_id");

                    b.Navigation("Governorate");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.InspectorAssignment", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.User", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_inspector_assignments__users_inspector_id");

                    b.HasOne("WheatTrace.Domain.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .HasConstraintName("f_k_inspector_assignments__shifts_shift_id");

                    b.HasOne("WheatTrace.Domain.Entities.StorageSite", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_inspector_assignments__storage_sites_site_id");

                    b.Navigation("Inspector");

                    b.Navigation("Shift");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.InspectorMessage", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.InspectorMessage", "ParentMessage")
                        .WithMany()
                        .HasForeignKey("ParentMessageId")
                        .HasConstraintName("f_k_inspector_messages_inspector_messages_parent_message_id");

                    b.HasOne("WheatTrace.Domain.Entities.User", "RecipientInspector")
                        .WithMany()
                        .HasForeignKey("RecipientInspectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_inspector_messages__users_recipient_inspector_id");

                    b.HasOne("WheatTrace.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .HasConstraintName("f_k_inspector_messages__users_sender_id");

                    b.HasOne("WheatTrace.Domain.Entities.StorageSite", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .HasConstraintName("f_k_inspector_messages__storage_sites_site_id");

                    b.Navigation("ParentMessage");

                    b.Navigation("RecipientInspector");

                    b.Navigation("Sender");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Rejection", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.DailyEntry", "DailyEntry")
                        .WithOne("Rejection")
                        .HasForeignKey("WheatTrace.Domain.Entities.Rejection", "DailyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_rejections_daily_entries_daily_entry_id");

                    b.Navigation("DailyEntry");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.SeasonSnapshot", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_season_snapshots__users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.SiteLifecycleEvent", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.User", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_site_lifecycle_events__users_recorded_by_id");

                    b.HasOne("WheatTrace.Domain.Entities.StorageSite", "Site")
                        .WithMany("LifecycleEvents")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_site_lifecycle_events__storage_sites_site_id");

                    b.Navigation("RecordedBy");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.StockTransfer", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.User", "AuthorizedBy")
                        .WithMany()
                        .HasForeignKey("AuthorizedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_stock_transfers__users_authorized_by_id");

                    b.HasOne("WheatTrace.Domain.Entities.StorageSite", "FromSite")
                        .WithMany("TransfersOut")
                        .HasForeignKey("FromSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_stock_transfers__storage_sites_from_site_id");

                    b.HasOne("WheatTrace.Domain.Entities.StorageSite", "ToSite")
                        .WithMany("TransfersIn")
                        .HasForeignKey("ToSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_stock_transfers__storage_sites_to_site_id");

                    b.HasOne("WheatTrace.Domain.Entities.SiteLifecycleEvent", "TriggerEvent")
                        .WithMany()
                        .HasForeignKey("TriggerEventId")
                        .HasConstraintName("f_k_stock_transfers_site_lifecycle_events_trigger_event_id");

                    b.Navigation("AuthorizedBy");

                    b.Navigation("FromSite");

                    b.Navigation("ToSite");

                    b.Navigation("TriggerEvent");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.StorageSite", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.Authority", "Authority")
                        .WithMany("StorageSites")
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_storage_sites_authorities_authority_id");

                    b.HasOne("WheatTrace.Domain.Entities.District", "District")
                        .WithMany("StorageSites")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("f_k_storage_sites_districts_district_id");

                    b.HasOne("WheatTrace.Domain.Entities.Governorate", "Governorate")
                        .WithMany("StorageSites")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_storage_sites_governorates_governorate_id");

                    b.Navigation("Authority");

                    b.Navigation("District");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.User", b =>
                {
                    b.HasOne("WheatTrace.Domain.Entities.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .HasConstraintName("f_k_users_governorates_governorate_id");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Authority", b =>
                {
                    b.Navigation("StorageSites");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.DailyEntry", b =>
                {
                    b.Navigation("Rejection");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.District", b =>
                {
                    b.Navigation("StorageSites");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.Governorate", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("StorageSites");
                });

            modelBuilder.Entity("WheatTrace.Domain.Entities.StorageSite", b =>
                {
                    b.Navigation("DailyEntries");

                    b.Navigation("LifecycleEvents");

                    b.Navigation("TransfersIn");

                    b.Navigation("TransfersOut");
                });
#pragma warning restore 612, 618
        }
    }
}
